// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXo7rVGJIAYQik3gCzYFaN2R7ffwpVJhQ',
    appId: '1:188781697122:web:7a33fadb88a3815bf1d93b',
    messagingSenderId: '188781697122',
    projectId: 'flutterchatapp1390',
    authDomain: 'flutterchatapp1390.firebaseapp.com',
    storageBucket: 'flutterchatapp1390.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAL4wMacRTb56STNeAn54TMXdH66FBhDTs',
    appId: '1:188781697122:android:5ae23af227347198f1d93b',
    messagingSenderId: '188781697122',
    projectId: 'flutterchatapp1390',
    storageBucket: 'flutterchatapp1390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeIzaCEH_I0bgWQHZMumUqLxbb22X6uLk',
    appId: '1:188781697122:ios:cd7cb519117de886f1d93b',
    messagingSenderId: '188781697122',
    projectId: 'flutterchatapp1390',
    storageBucket: 'flutterchatapp1390.appspot.com',
    iosClientId: '188781697122-97ng6hnjhinvatbknrgjdbb9iqglbslg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeIzaCEH_I0bgWQHZMumUqLxbb22X6uLk',
    appId: '1:188781697122:ios:cd7cb519117de886f1d93b',
    messagingSenderId: '188781697122',
    projectId: 'flutterchatapp1390',
    storageBucket: 'flutterchatapp1390.appspot.com',
    iosClientId: '188781697122-97ng6hnjhinvatbknrgjdbb9iqglbslg.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
